//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtendedCalculationResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendedCalculationResult">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CalculationResult">
 *       &lt;sequence>
 *         &lt;element name="calculationDataCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CalculationData" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CalculationData" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendedCalculationResult", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "calculationDataCollection"
})
public class ExtendedCalculationResult
    extends CalculationResult
{

    protected ExtendedCalculationResult.CalculationDataCollection calculationDataCollection;

    /**
     * Gets the value of the calculationDataCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ExtendedCalculationResult.CalculationDataCollection }
     *     
     */
    public ExtendedCalculationResult.CalculationDataCollection getCalculationDataCollection() {
        return calculationDataCollection;
    }

    /**
     * Sets the value of the calculationDataCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtendedCalculationResult.CalculationDataCollection }
     *     
     */
    public void setCalculationDataCollection(ExtendedCalculationResult.CalculationDataCollection value) {
        this.calculationDataCollection = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CalculationData" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CalculationData" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "calculationData"
    })
    public static class CalculationDataCollection {

        @XmlElement(name = "CalculationData", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<CalculationData> calculationData;

        /**
         * Gets the value of the calculationData property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the calculationData property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCalculationData().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CalculationData }
         * 
         * 
         */
        public List<CalculationData> getCalculationData() {
            if (calculationData == null) {
                calculationData = new ArrayList<CalculationData>();
            }
            return this.calculationData;
        }

    }

}
