//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImagingPhysicalEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImagingPhysicalEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}Entity">
 *       &lt;sequence>
 *         &lt;element name="typeCode" type="{uri:iso.org:21090}CD" maxOccurs="unbounded"/>
 *         &lt;element name="questionTypeCode" type="{uri:iso.org:21090}CD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="isPresent" type="{uri:iso.org:21090}BL" minOccurs="0"/>
 *         &lt;element name="annotatorConfidence" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="label" type="{uri:iso.org:21090}ST" minOccurs="0"/>
 *         &lt;element name="questionIndex" type="{uri:iso.org:21090}INT" minOccurs="0"/>
 *         &lt;element name="comment" type="{uri:iso.org:21090}ST" minOccurs="0"/>
 *         &lt;element name="imagingPhysicalEntityCharacteristicCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImagingPhysicalEntityCharacteristic" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagingPhysicalEntityCharacteristic" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="imagingObservationCharacteristicCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImagingObservationCharacteristic" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagingObservationCharacteristic" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImagingPhysicalEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "typeCode",
    "questionTypeCode",
    "isPresent",
    "annotatorConfidence",
    "label",
    "questionIndex",
    "comment",
    "imagingPhysicalEntityCharacteristicCollection",
    "imagingObservationCharacteristicCollection"
})
public class ImagingPhysicalEntity
    extends Entity
{

    @XmlElement(required = true)
    protected List<CD> typeCode;
    protected List<CD> questionTypeCode;
    protected BL isPresent;
    protected REAL annotatorConfidence;
    protected ST label;
    protected INT questionIndex;
    protected ST comment;
    protected ImagingPhysicalEntity.ImagingPhysicalEntityCharacteristicCollection imagingPhysicalEntityCharacteristicCollection;
    protected ImagingPhysicalEntity.ImagingObservationCharacteristicCollection imagingObservationCharacteristicCollection;

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CD }
     * 
     * 
     */
    public List<CD> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CD>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the questionTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questionTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestionTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CD }
     * 
     * 
     */
    public List<CD> getQuestionTypeCode() {
        if (questionTypeCode == null) {
            questionTypeCode = new ArrayList<CD>();
        }
        return this.questionTypeCode;
    }

    /**
     * Gets the value of the isPresent property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getIsPresent() {
        return isPresent;
    }

    /**
     * Sets the value of the isPresent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setIsPresent(BL value) {
        this.isPresent = value;
    }

    /**
     * Gets the value of the annotatorConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getAnnotatorConfidence() {
        return annotatorConfidence;
    }

    /**
     * Sets the value of the annotatorConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setAnnotatorConfidence(REAL value) {
        this.annotatorConfidence = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setLabel(ST value) {
        this.label = value;
    }

    /**
     * Gets the value of the questionIndex property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getQuestionIndex() {
        return questionIndex;
    }

    /**
     * Sets the value of the questionIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setQuestionIndex(INT value) {
        this.questionIndex = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setComment(ST value) {
        this.comment = value;
    }

    /**
     * Gets the value of the imagingPhysicalEntityCharacteristicCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ImagingPhysicalEntity.ImagingPhysicalEntityCharacteristicCollection }
     *     
     */
    public ImagingPhysicalEntity.ImagingPhysicalEntityCharacteristicCollection getImagingPhysicalEntityCharacteristicCollection() {
        return imagingPhysicalEntityCharacteristicCollection;
    }

    /**
     * Sets the value of the imagingPhysicalEntityCharacteristicCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagingPhysicalEntity.ImagingPhysicalEntityCharacteristicCollection }
     *     
     */
    public void setImagingPhysicalEntityCharacteristicCollection(ImagingPhysicalEntity.ImagingPhysicalEntityCharacteristicCollection value) {
        this.imagingPhysicalEntityCharacteristicCollection = value;
    }

    /**
     * Gets the value of the imagingObservationCharacteristicCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ImagingPhysicalEntity.ImagingObservationCharacteristicCollection }
     *     
     */
    public ImagingPhysicalEntity.ImagingObservationCharacteristicCollection getImagingObservationCharacteristicCollection() {
        return imagingObservationCharacteristicCollection;
    }

    /**
     * Sets the value of the imagingObservationCharacteristicCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagingPhysicalEntity.ImagingObservationCharacteristicCollection }
     *     
     */
    public void setImagingObservationCharacteristicCollection(ImagingPhysicalEntity.ImagingObservationCharacteristicCollection value) {
        this.imagingObservationCharacteristicCollection = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImagingObservationCharacteristic" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagingObservationCharacteristic" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imagingObservationCharacteristic"
    })
    public static class ImagingObservationCharacteristicCollection {

        @XmlElement(name = "ImagingObservationCharacteristic", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<ImagingObservationCharacteristic> imagingObservationCharacteristic;

        /**
         * Gets the value of the imagingObservationCharacteristic property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imagingObservationCharacteristic property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImagingObservationCharacteristic().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImagingObservationCharacteristic }
         * 
         * 
         */
        public List<ImagingObservationCharacteristic> getImagingObservationCharacteristic() {
            if (imagingObservationCharacteristic == null) {
                imagingObservationCharacteristic = new ArrayList<ImagingObservationCharacteristic>();
            }
            return this.imagingObservationCharacteristic;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImagingPhysicalEntityCharacteristic" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagingPhysicalEntityCharacteristic" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imagingPhysicalEntityCharacteristic"
    })
    public static class ImagingPhysicalEntityCharacteristicCollection {

        @XmlElement(name = "ImagingPhysicalEntityCharacteristic", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<ImagingPhysicalEntityCharacteristic> imagingPhysicalEntityCharacteristic;

        /**
         * Gets the value of the imagingPhysicalEntityCharacteristic property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imagingPhysicalEntityCharacteristic property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImagingPhysicalEntityCharacteristic().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImagingPhysicalEntityCharacteristic }
         * 
         * 
         */
        public List<ImagingPhysicalEntityCharacteristic> getImagingPhysicalEntityCharacteristic() {
            if (imagingPhysicalEntityCharacteristic == null) {
                imagingPhysicalEntityCharacteristic = new ArrayList<ImagingPhysicalEntityCharacteristic>();
            }
            return this.imagingPhysicalEntityCharacteristic;
        }

    }

}
