//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferencedDicomObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReferencedDicomObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="modality" type="{uri:iso.org:21090}CD"/>
 *         &lt;element name="sopInstanceUid" type="{uri:iso.org:21090}II"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferencedDicomObject", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "modality",
    "sopInstanceUid"
})
public class ReferencedDicomObject {

    @XmlElement(required = true)
    protected CD modality;
    @XmlElement(required = true)
    protected II sopInstanceUid;

    /**
     * Gets the value of the modality property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getModality() {
        return modality;
    }

    /**
     * Sets the value of the modality property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setModality(CD value) {
        this.modality = value;
    }

    /**
     * Gets the value of the sopInstanceUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getSopInstanceUid() {
        return sopInstanceUid;
    }

    /**
     * Sets the value of the sopInstanceUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setSopInstanceUid(II value) {
        this.sopInstanceUid = value;
    }

}
