//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotationCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uniqueIdentifier" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="description" type="{uri:iso.org:21090}ST" minOccurs="0"/>
 *         &lt;element name="dateTime" type="{uri:iso.org:21090}TS"/>
 *         &lt;element name="user" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}User" minOccurs="0"/>
 *         &lt;element name="equipment" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}Equipment" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="aimVersion" use="required" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AimVersion" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotationCollection", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "uniqueIdentifier",
    "description",
    "dateTime",
    "user",
    "equipment"
})
@XmlSeeAlso({
    ImageAnnotationCollection.class,
    AnnotationOfAnnotationCollection.class
})
public abstract class AnnotationCollection {

    @XmlElement(required = true)
    protected II uniqueIdentifier;
    protected ST description;
    @XmlElement(required = true)
    protected TS dateTime;
    protected User user;
    protected Equipment equipment;
    @XmlAttribute(required = true)
    protected AimVersion aimVersion;

    /**
     * Gets the value of the uniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getUniqueIdentifier() {
        return uniqueIdentifier;
    }

    /**
     * Sets the value of the uniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setUniqueIdentifier(II value) {
        this.uniqueIdentifier = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setDescription(ST value) {
        this.description = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setDateTime(TS value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

    /**
     * Gets the value of the equipment property.
     * 
     * @return
     *     possible object is
     *     {@link Equipment }
     *     
     */
    public Equipment getEquipment() {
        return equipment;
    }

    /**
     * Sets the value of the equipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Equipment }
     *     
     */
    public void setEquipment(Equipment value) {
        this.equipment = value;
    }

    /**
     * Gets the value of the aimVersion property.
     * 
     * @return
     *     possible object is
     *     {@link AimVersion }
     *     
     */
    public AimVersion getAimVersion() {
        return aimVersion;
    }

    /**
     * Sets the value of the aimVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link AimVersion }
     *     
     */
    public void setAimVersion(AimVersion value) {
        this.aimVersion = value;
    }

}
