//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Numerical complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Numerical">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CharacteristicQuantification">
 *       &lt;sequence>
 *         &lt;element name="ucumString" type="{uri:iso.org:21090}ST"/>
 *         &lt;element name="value" type="{uri:iso.org:21090}REAL"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operator" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ComparisonOperator" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Numerical", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "ucumString",
    "value"
})
public class Numerical
    extends CharacteristicQuantification
{

    @XmlElement(required = true)
    protected ST ucumString;
    @XmlElement(required = true)
    protected REAL value;
    @XmlAttribute
    protected ComparisonOperator operator;

    /**
     * Gets the value of the ucumString property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getUcumString() {
        return ucumString;
    }

    /**
     * Sets the value of the ucumString property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setUcumString(ST value) {
        this.ucumString = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setValue(REAL value) {
        this.value = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link ComparisonOperator }
     *     
     */
    public ComparisonOperator getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparisonOperator }
     *     
     */
    public void setOperator(ComparisonOperator value) {
        this.operator = value;
    }

}
