//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DicomSegmentationEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DicomSegmentationEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}SegmentationEntity">
 *       &lt;sequence>
 *         &lt;element name="sopInstanceUid" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="sopClassUid" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="referencedSopInstanceUid" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="segmentNumber" type="{uri:iso.org:21090}INT"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DicomSegmentationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "sopInstanceUid",
    "sopClassUid",
    "referencedSopInstanceUid",
    "segmentNumber"
})
public class DicomSegmentationEntity
    extends SegmentationEntity
{

    @XmlElement(required = true)
    protected II sopInstanceUid;
    @XmlElement(required = true)
    protected II sopClassUid;
    @XmlElement(required = true)
    protected II referencedSopInstanceUid;
    @XmlElement(required = true)
    protected INT segmentNumber;

    /**
     * Gets the value of the sopInstanceUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getSopInstanceUid() {
        return sopInstanceUid;
    }

    /**
     * Sets the value of the sopInstanceUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setSopInstanceUid(II value) {
        this.sopInstanceUid = value;
    }

    /**
     * Gets the value of the sopClassUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getSopClassUid() {
        return sopClassUid;
    }

    /**
     * Sets the value of the sopClassUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setSopClassUid(II value) {
        this.sopClassUid = value;
    }

    /**
     * Gets the value of the referencedSopInstanceUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getReferencedSopInstanceUid() {
        return referencedSopInstanceUid;
    }

    /**
     * Sets the value of the referencedSopInstanceUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setReferencedSopInstanceUid(II value) {
        this.referencedSopInstanceUid = value;
    }

    /**
     * Gets the value of the segmentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getSegmentNumber() {
        return segmentNumber;
    }

    /**
     * Sets the value of the segmentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setSegmentNumber(INT value) {
        this.segmentNumber = value;
    }

}
