//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Interval complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Interval">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CharacteristicQuantification">
 *       &lt;sequence>
 *         &lt;element name="minValue" type="{uri:iso.org:21090}REAL"/>
 *         &lt;element name="maxValue" type="{uri:iso.org:21090}REAL"/>
 *         &lt;element name="ucumString" type="{uri:iso.org:21090}ST"/>
 *       &lt;/sequence>
 *       &lt;attribute name="minOperator" use="required" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ComparisonOperator" />
 *       &lt;attribute name="maxOperator" use="required" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ComparisonOperator" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Interval", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "minValue",
    "maxValue",
    "ucumString"
})
public class Interval
    extends CharacteristicQuantification
{

    @XmlElement(required = true)
    protected REAL minValue;
    @XmlElement(required = true)
    protected REAL maxValue;
    @XmlElement(required = true)
    protected ST ucumString;
    @XmlAttribute(required = true)
    protected ComparisonOperator minOperator;
    @XmlAttribute(required = true)
    protected ComparisonOperator maxOperator;

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setMinValue(REAL value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setMaxValue(REAL value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the ucumString property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getUcumString() {
        return ucumString;
    }

    /**
     * Sets the value of the ucumString property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setUcumString(ST value) {
        this.ucumString = value;
    }

    /**
     * Gets the value of the minOperator property.
     * 
     * @return
     *     possible object is
     *     {@link ComparisonOperator }
     *     
     */
    public ComparisonOperator getMinOperator() {
        return minOperator;
    }

    /**
     * Sets the value of the minOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparisonOperator }
     *     
     */
    public void setMinOperator(ComparisonOperator value) {
        this.minOperator = value;
    }

    /**
     * Gets the value of the maxOperator property.
     * 
     * @return
     *     possible object is
     *     {@link ComparisonOperator }
     *     
     */
    public ComparisonOperator getMaxOperator() {
        return maxOperator;
    }

    /**
     * Sets the value of the maxOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComparisonOperator }
     *     
     */
    public void setMaxOperator(ComparisonOperator value) {
        this.maxOperator = value;
    }

}
