//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationStatement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotationStatement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subjectUniqueIdentifier" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="objectUniqueIdentifier" type="{uri:iso.org:21090}II"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotationStatement", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "subjectUniqueIdentifier",
    "objectUniqueIdentifier"
})
@XmlSeeAlso({
    ImagingObservationEntityIsFoundInImagingPhysicalEntityStatement.class,
    AnnotationEntityHasPerformedTaskContextEntityStatement.class,
    CalculationEntityReferencesCalculationEntityStatement.class,
    CalculationEntityUsesCalculationEntityStatement.class,
    ImagingObservationEntityHasCalculationEntityStatement.class,
    ImagingPhysicalEntityHasCalculationEntityStatement.class,
    ImagingPhysicalEntityHasImagingObservationEntityStatement.class,
    AnnotationEntityHasPlannedTaskContextEntityStatement.class,
    ImageAnnotationIsComparedWithAnnotationOfAnnotationStatement.class,
    AnnotationOfAnnotationIsComparedWithAnnotationOfAnnotationStatement.class,
    AnnotationOfAnnotationStatement.class,
    ImageAnnotationStatement.class
})
public abstract class AnnotationStatement {

    @XmlElement(required = true)
    protected II subjectUniqueIdentifier;
    @XmlElement(required = true)
    protected II objectUniqueIdentifier;

    /**
     * Gets the value of the subjectUniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getSubjectUniqueIdentifier() {
        return subjectUniqueIdentifier;
    }

    /**
     * Sets the value of the subjectUniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setSubjectUniqueIdentifier(II value) {
        this.subjectUniqueIdentifier = value;
    }

    /**
     * Gets the value of the objectUniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getObjectUniqueIdentifier() {
        return objectUniqueIdentifier;
    }

    /**
     * Sets the value of the objectUniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setObjectUniqueIdentifier(II value) {
        this.objectUniqueIdentifier = value;
    }

}
