//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnnotationEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotationEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}Entity">
 *       &lt;sequence>
 *         &lt;element name="typeCode" type="{uri:iso.org:21090}CD" maxOccurs="unbounded"/>
 *         &lt;element name="dateTime" type="{uri:iso.org:21090}TS"/>
 *         &lt;element name="name" type="{uri:iso.org:21090}ST"/>
 *         &lt;element name="comment" type="{uri:iso.org:21090}ST" minOccurs="0"/>
 *         &lt;element name="precedentReferencedAnnotationUid" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="templateUid" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="auditTrailCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AuditTrail" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AuditTrail" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="imagingPhysicalEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImagingPhysicalEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagingPhysicalEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="calculationEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CalculationEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CalculationEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="inferenceEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="InferenceEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}InferenceEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="annotationRoleEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AnnotationRoleEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AnnotationRoleEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="lesionObservationEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="LesionObservationEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}LesionObservationEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="imagingObservationEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImagingObservationEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagingObservationEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="taskContextEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TaskContextEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}TaskContextEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "typeCode",
    "dateTime",
    "name",
    "comment",
    "precedentReferencedAnnotationUid",
    "templateUid",
    "auditTrailCollection",
    "imagingPhysicalEntityCollection",
    "calculationEntityCollection",
    "inferenceEntityCollection",
    "annotationRoleEntityCollection",
    "lesionObservationEntityCollection",
    "imagingObservationEntityCollection",
    "taskContextEntityCollection"
})
@XmlSeeAlso({
    ImageAnnotation.class,
    AnnotationOfAnnotation.class
})
public abstract class AnnotationEntity
    extends Entity
{

    @XmlElement(required = true)
    protected List<CD> typeCode;
    @XmlElement(required = true)
    protected TS dateTime;
    @XmlElement(required = true)
    protected ST name;
    protected ST comment;
    protected II precedentReferencedAnnotationUid;
    protected II templateUid;
    protected AnnotationEntity.AuditTrailCollection auditTrailCollection;
    protected AnnotationEntity.ImagingPhysicalEntityCollection imagingPhysicalEntityCollection;
    protected AnnotationEntity.CalculationEntityCollection calculationEntityCollection;
    protected AnnotationEntity.InferenceEntityCollection inferenceEntityCollection;
    protected AnnotationEntity.AnnotationRoleEntityCollection annotationRoleEntityCollection;
    protected AnnotationEntity.LesionObservationEntityCollection lesionObservationEntityCollection;
    protected AnnotationEntity.ImagingObservationEntityCollection imagingObservationEntityCollection;
    protected AnnotationEntity.TaskContextEntityCollection taskContextEntityCollection;

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CD }
     * 
     * 
     */
    public List<CD> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CD>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link TS }
     *     
     */
    public TS getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TS }
     *     
     */
    public void setDateTime(TS value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setName(ST value) {
        this.name = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setComment(ST value) {
        this.comment = value;
    }

    /**
     * Gets the value of the precedentReferencedAnnotationUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getPrecedentReferencedAnnotationUid() {
        return precedentReferencedAnnotationUid;
    }

    /**
     * Sets the value of the precedentReferencedAnnotationUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setPrecedentReferencedAnnotationUid(II value) {
        this.precedentReferencedAnnotationUid = value;
    }

    /**
     * Gets the value of the templateUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getTemplateUid() {
        return templateUid;
    }

    /**
     * Sets the value of the templateUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setTemplateUid(II value) {
        this.templateUid = value;
    }

    /**
     * Gets the value of the auditTrailCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationEntity.AuditTrailCollection }
     *     
     */
    public AnnotationEntity.AuditTrailCollection getAuditTrailCollection() {
        return auditTrailCollection;
    }

    /**
     * Sets the value of the auditTrailCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationEntity.AuditTrailCollection }
     *     
     */
    public void setAuditTrailCollection(AnnotationEntity.AuditTrailCollection value) {
        this.auditTrailCollection = value;
    }

    /**
     * Gets the value of the imagingPhysicalEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationEntity.ImagingPhysicalEntityCollection }
     *     
     */
    public AnnotationEntity.ImagingPhysicalEntityCollection getImagingPhysicalEntityCollection() {
        return imagingPhysicalEntityCollection;
    }

    /**
     * Sets the value of the imagingPhysicalEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationEntity.ImagingPhysicalEntityCollection }
     *     
     */
    public void setImagingPhysicalEntityCollection(AnnotationEntity.ImagingPhysicalEntityCollection value) {
        this.imagingPhysicalEntityCollection = value;
    }

    /**
     * Gets the value of the calculationEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationEntity.CalculationEntityCollection }
     *     
     */
    public AnnotationEntity.CalculationEntityCollection getCalculationEntityCollection() {
        return calculationEntityCollection;
    }

    /**
     * Sets the value of the calculationEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationEntity.CalculationEntityCollection }
     *     
     */
    public void setCalculationEntityCollection(AnnotationEntity.CalculationEntityCollection value) {
        this.calculationEntityCollection = value;
    }

    /**
     * Gets the value of the inferenceEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationEntity.InferenceEntityCollection }
     *     
     */
    public AnnotationEntity.InferenceEntityCollection getInferenceEntityCollection() {
        return inferenceEntityCollection;
    }

    /**
     * Sets the value of the inferenceEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationEntity.InferenceEntityCollection }
     *     
     */
    public void setInferenceEntityCollection(AnnotationEntity.InferenceEntityCollection value) {
        this.inferenceEntityCollection = value;
    }

    /**
     * Gets the value of the annotationRoleEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationEntity.AnnotationRoleEntityCollection }
     *     
     */
    public AnnotationEntity.AnnotationRoleEntityCollection getAnnotationRoleEntityCollection() {
        return annotationRoleEntityCollection;
    }

    /**
     * Sets the value of the annotationRoleEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationEntity.AnnotationRoleEntityCollection }
     *     
     */
    public void setAnnotationRoleEntityCollection(AnnotationEntity.AnnotationRoleEntityCollection value) {
        this.annotationRoleEntityCollection = value;
    }

    /**
     * Gets the value of the lesionObservationEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationEntity.LesionObservationEntityCollection }
     *     
     */
    public AnnotationEntity.LesionObservationEntityCollection getLesionObservationEntityCollection() {
        return lesionObservationEntityCollection;
    }

    /**
     * Sets the value of the lesionObservationEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationEntity.LesionObservationEntityCollection }
     *     
     */
    public void setLesionObservationEntityCollection(AnnotationEntity.LesionObservationEntityCollection value) {
        this.lesionObservationEntityCollection = value;
    }

    /**
     * Gets the value of the imagingObservationEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationEntity.ImagingObservationEntityCollection }
     *     
     */
    public AnnotationEntity.ImagingObservationEntityCollection getImagingObservationEntityCollection() {
        return imagingObservationEntityCollection;
    }

    /**
     * Sets the value of the imagingObservationEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationEntity.ImagingObservationEntityCollection }
     *     
     */
    public void setImagingObservationEntityCollection(AnnotationEntity.ImagingObservationEntityCollection value) {
        this.imagingObservationEntityCollection = value;
    }

    /**
     * Gets the value of the taskContextEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationEntity.TaskContextEntityCollection }
     *     
     */
    public AnnotationEntity.TaskContextEntityCollection getTaskContextEntityCollection() {
        return taskContextEntityCollection;
    }

    /**
     * Sets the value of the taskContextEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationEntity.TaskContextEntityCollection }
     *     
     */
    public void setTaskContextEntityCollection(AnnotationEntity.TaskContextEntityCollection value) {
        this.taskContextEntityCollection = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AnnotationRoleEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AnnotationRoleEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "annotationRoleEntity"
    })
    public static class AnnotationRoleEntityCollection {

        @XmlElement(name = "AnnotationRoleEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<AnnotationRoleEntity> annotationRoleEntity;

        /**
         * Gets the value of the annotationRoleEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the annotationRoleEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAnnotationRoleEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnnotationRoleEntity }
         * 
         * 
         */
        public List<AnnotationRoleEntity> getAnnotationRoleEntity() {
            if (annotationRoleEntity == null) {
                annotationRoleEntity = new ArrayList<AnnotationRoleEntity>();
            }
            return this.annotationRoleEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AuditTrail" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AuditTrail" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "auditTrail"
    })
    public static class AuditTrailCollection {

        @XmlElement(name = "AuditTrail", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<AuditTrail> auditTrail;

        /**
         * Gets the value of the auditTrail property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the auditTrail property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAuditTrail().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AuditTrail }
         * 
         * 
         */
        public List<AuditTrail> getAuditTrail() {
            if (auditTrail == null) {
                auditTrail = new ArrayList<AuditTrail>();
            }
            return this.auditTrail;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CalculationEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CalculationEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "calculationEntity"
    })
    public static class CalculationEntityCollection {

        @XmlElement(name = "CalculationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<CalculationEntity> calculationEntity;

        /**
         * Gets the value of the calculationEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the calculationEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCalculationEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CalculationEntity }
         * 
         * 
         */
        public List<CalculationEntity> getCalculationEntity() {
            if (calculationEntity == null) {
                calculationEntity = new ArrayList<CalculationEntity>();
            }
            return this.calculationEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImagingObservationEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagingObservationEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imagingObservationEntity"
    })
    public static class ImagingObservationEntityCollection {

        @XmlElement(name = "ImagingObservationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<ImagingObservationEntity> imagingObservationEntity;

        /**
         * Gets the value of the imagingObservationEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imagingObservationEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImagingObservationEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImagingObservationEntity }
         * 
         * 
         */
        public List<ImagingObservationEntity> getImagingObservationEntity() {
            if (imagingObservationEntity == null) {
                imagingObservationEntity = new ArrayList<ImagingObservationEntity>();
            }
            return this.imagingObservationEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImagingPhysicalEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagingPhysicalEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imagingPhysicalEntity"
    })
    public static class ImagingPhysicalEntityCollection {

        @XmlElement(name = "ImagingPhysicalEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<ImagingPhysicalEntity> imagingPhysicalEntity;

        /**
         * Gets the value of the imagingPhysicalEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imagingPhysicalEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImagingPhysicalEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImagingPhysicalEntity }
         * 
         * 
         */
        public List<ImagingPhysicalEntity> getImagingPhysicalEntity() {
            if (imagingPhysicalEntity == null) {
                imagingPhysicalEntity = new ArrayList<ImagingPhysicalEntity>();
            }
            return this.imagingPhysicalEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="InferenceEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}InferenceEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inferenceEntity"
    })
    public static class InferenceEntityCollection {

        @XmlElement(name = "InferenceEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<InferenceEntity> inferenceEntity;

        /**
         * Gets the value of the inferenceEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the inferenceEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInferenceEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link InferenceEntity }
         * 
         * 
         */
        public List<InferenceEntity> getInferenceEntity() {
            if (inferenceEntity == null) {
                inferenceEntity = new ArrayList<InferenceEntity>();
            }
            return this.inferenceEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="LesionObservationEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}LesionObservationEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lesionObservationEntity"
    })
    public static class LesionObservationEntityCollection {

        @XmlElement(name = "LesionObservationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<LesionObservationEntity> lesionObservationEntity;

        /**
         * Gets the value of the lesionObservationEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lesionObservationEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLesionObservationEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LesionObservationEntity }
         * 
         * 
         */
        public List<LesionObservationEntity> getLesionObservationEntity() {
            if (lesionObservationEntity == null) {
                lesionObservationEntity = new ArrayList<LesionObservationEntity>();
            }
            return this.lesionObservationEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TaskContextEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}TaskContextEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "taskContextEntity"
    })
    public static class TaskContextEntityCollection {

        @XmlElement(name = "TaskContextEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<TaskContextEntity> taskContextEntity;

        /**
         * Gets the value of the taskContextEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the taskContextEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTaskContextEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link TaskContextEntity }
         * 
         * 
         */
        public List<TaskContextEntity> getTaskContextEntity() {
            if (taskContextEntity == null) {
                taskContextEntity = new ArrayList<TaskContextEntity>();
            }
            return this.taskContextEntity;
        }

    }

}
