//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalculationEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalculationEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}Entity">
 *       &lt;sequence>
 *         &lt;element name="typeCode" type="{uri:iso.org:21090}CD" maxOccurs="unbounded"/>
 *         &lt;element name="questionTypeCode" type="{uri:iso.org:21090}CD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{uri:iso.org:21090}ST"/>
 *         &lt;element name="mathML" type="{uri:iso.org:21090}ST" minOccurs="0"/>
 *         &lt;element name="questionIndex" type="{uri:iso.org:21090}INT" minOccurs="0"/>
 *         &lt;element name="calculationResultCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="CalculationResult" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CalculationResult" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="algorithm" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}Algorithm" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalculationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "typeCode",
    "questionTypeCode",
    "description",
    "mathML",
    "questionIndex",
    "calculationResultCollection",
    "algorithm"
})
public class CalculationEntity
    extends Entity
{

    @XmlElement(required = true)
    protected List<CD> typeCode;
    protected List<CD> questionTypeCode;
    @XmlElement(required = true)
    protected ST description;
    protected ST mathML;
    protected INT questionIndex;
    protected CalculationEntity.CalculationResultCollection calculationResultCollection;
    protected Algorithm algorithm;

    /**
     * Gets the value of the typeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CD }
     * 
     * 
     */
    public List<CD> getTypeCode() {
        if (typeCode == null) {
            typeCode = new ArrayList<CD>();
        }
        return this.typeCode;
    }

    /**
     * Gets the value of the questionTypeCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the questionTypeCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getQuestionTypeCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CD }
     * 
     * 
     */
    public List<CD> getQuestionTypeCode() {
        if (questionTypeCode == null) {
            questionTypeCode = new ArrayList<CD>();
        }
        return this.questionTypeCode;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setDescription(ST value) {
        this.description = value;
    }

    /**
     * Gets the value of the mathML property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getMathML() {
        return mathML;
    }

    /**
     * Sets the value of the mathML property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setMathML(ST value) {
        this.mathML = value;
    }

    /**
     * Gets the value of the questionIndex property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getQuestionIndex() {
        return questionIndex;
    }

    /**
     * Sets the value of the questionIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setQuestionIndex(INT value) {
        this.questionIndex = value;
    }

    /**
     * Gets the value of the calculationResultCollection property.
     * 
     * @return
     *     possible object is
     *     {@link CalculationEntity.CalculationResultCollection }
     *     
     */
    public CalculationEntity.CalculationResultCollection getCalculationResultCollection() {
        return calculationResultCollection;
    }

    /**
     * Sets the value of the calculationResultCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculationEntity.CalculationResultCollection }
     *     
     */
    public void setCalculationResultCollection(CalculationEntity.CalculationResultCollection value) {
        this.calculationResultCollection = value;
    }

    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *     possible object is
     *     {@link Algorithm }
     *     
     */
    public Algorithm getAlgorithm() {
        return algorithm;
    }

    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Algorithm }
     *     
     */
    public void setAlgorithm(Algorithm value) {
        this.algorithm = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="CalculationResult" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CalculationResult" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "calculationResult"
    })
    public static class CalculationResultCollection {

        @XmlElement(name = "CalculationResult", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<CalculationResult> calculationResult;

        /**
         * Gets the value of the calculationResult property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the calculationResult property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCalculationResult().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CalculationResult }
         * 
         * 
         */
        public List<CalculationResult> getCalculationResult() {
            if (calculationResult == null) {
                calculationResult = new ArrayList<CalculationResult>();
            }
            return this.calculationResult;
        }

    }

}
