//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeneralLesionObservationEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralLesionObservationEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}LesionObservationEntity">
 *       &lt;sequence>
 *         &lt;element name="trackingIdentifier" type="{uri:iso.org:21090}ST"/>
 *         &lt;element name="lesionType" type="{uri:iso.org:21090}CD"/>
 *         &lt;element name="reconstructionInterval" type="{uri:iso.org:21090}CD" minOccurs="0"/>
 *         &lt;element name="laterality" type="{uri:iso.org:21090}CD" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralLesionObservationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "trackingIdentifier",
    "lesionType",
    "reconstructionInterval",
    "laterality"
})
public class GeneralLesionObservationEntity
    extends LesionObservationEntity
{

    @XmlElement(required = true)
    protected ST trackingIdentifier;
    @XmlElement(required = true)
    protected CD lesionType;
    protected CD reconstructionInterval;
    protected CD laterality;

    /**
     * Gets the value of the trackingIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link ST }
     *     
     */
    public ST getTrackingIdentifier() {
        return trackingIdentifier;
    }

    /**
     * Sets the value of the trackingIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ST }
     *     
     */
    public void setTrackingIdentifier(ST value) {
        this.trackingIdentifier = value;
    }

    /**
     * Gets the value of the lesionType property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getLesionType() {
        return lesionType;
    }

    /**
     * Sets the value of the lesionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setLesionType(CD value) {
        this.lesionType = value;
    }

    /**
     * Gets the value of the reconstructionInterval property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getReconstructionInterval() {
        return reconstructionInterval;
    }

    /**
     * Sets the value of the reconstructionInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setReconstructionInterval(CD value) {
        this.reconstructionInterval = value;
    }

    /**
     * Gets the value of the laterality property.
     * 
     * @return
     *     possible object is
     *     {@link CD }
     *     
     */
    public CD getLaterality() {
        return laterality;
    }

    /**
     * Sets the value of the laterality property.
     * 
     * @param value
     *     allowed object is
     *     {@link CD }
     *     
     */
    public void setLaterality(CD value) {
        this.laterality = value;
    }

}
