//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImagePlane complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImagePlane">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rowImageOrientationX" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="rowImageOrientationY" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="rowImageOrientationZ" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="columnImageOrientationX" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="columnImageOrientationY" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="columnImageOrientationZ" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="verticalPixelSpacing" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="horizontalPixelSpacing" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="sliceThickness" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="imagePositionX" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="imagePositionY" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *         &lt;element name="imagePositionZ" type="{uri:iso.org:21090}REAL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImagePlane", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "rowImageOrientationX",
    "rowImageOrientationY",
    "rowImageOrientationZ",
    "columnImageOrientationX",
    "columnImageOrientationY",
    "columnImageOrientationZ",
    "verticalPixelSpacing",
    "horizontalPixelSpacing",
    "sliceThickness",
    "imagePositionX",
    "imagePositionY",
    "imagePositionZ"
})
public class ImagePlane {

    protected REAL rowImageOrientationX;
    protected REAL rowImageOrientationY;
    protected REAL rowImageOrientationZ;
    protected REAL columnImageOrientationX;
    protected REAL columnImageOrientationY;
    protected REAL columnImageOrientationZ;
    protected REAL verticalPixelSpacing;
    protected REAL horizontalPixelSpacing;
    protected REAL sliceThickness;
    protected REAL imagePositionX;
    protected REAL imagePositionY;
    protected REAL imagePositionZ;

    /**
     * Gets the value of the rowImageOrientationX property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getRowImageOrientationX() {
        return rowImageOrientationX;
    }

    /**
     * Sets the value of the rowImageOrientationX property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setRowImageOrientationX(REAL value) {
        this.rowImageOrientationX = value;
    }

    /**
     * Gets the value of the rowImageOrientationY property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getRowImageOrientationY() {
        return rowImageOrientationY;
    }

    /**
     * Sets the value of the rowImageOrientationY property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setRowImageOrientationY(REAL value) {
        this.rowImageOrientationY = value;
    }

    /**
     * Gets the value of the rowImageOrientationZ property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getRowImageOrientationZ() {
        return rowImageOrientationZ;
    }

    /**
     * Sets the value of the rowImageOrientationZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setRowImageOrientationZ(REAL value) {
        this.rowImageOrientationZ = value;
    }

    /**
     * Gets the value of the columnImageOrientationX property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getColumnImageOrientationX() {
        return columnImageOrientationX;
    }

    /**
     * Sets the value of the columnImageOrientationX property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setColumnImageOrientationX(REAL value) {
        this.columnImageOrientationX = value;
    }

    /**
     * Gets the value of the columnImageOrientationY property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getColumnImageOrientationY() {
        return columnImageOrientationY;
    }

    /**
     * Sets the value of the columnImageOrientationY property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setColumnImageOrientationY(REAL value) {
        this.columnImageOrientationY = value;
    }

    /**
     * Gets the value of the columnImageOrientationZ property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getColumnImageOrientationZ() {
        return columnImageOrientationZ;
    }

    /**
     * Sets the value of the columnImageOrientationZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setColumnImageOrientationZ(REAL value) {
        this.columnImageOrientationZ = value;
    }

    /**
     * Gets the value of the verticalPixelSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getVerticalPixelSpacing() {
        return verticalPixelSpacing;
    }

    /**
     * Sets the value of the verticalPixelSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setVerticalPixelSpacing(REAL value) {
        this.verticalPixelSpacing = value;
    }

    /**
     * Gets the value of the horizontalPixelSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getHorizontalPixelSpacing() {
        return horizontalPixelSpacing;
    }

    /**
     * Sets the value of the horizontalPixelSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setHorizontalPixelSpacing(REAL value) {
        this.horizontalPixelSpacing = value;
    }

    /**
     * Gets the value of the sliceThickness property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getSliceThickness() {
        return sliceThickness;
    }

    /**
     * Sets the value of the sliceThickness property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setSliceThickness(REAL value) {
        this.sliceThickness = value;
    }

    /**
     * Gets the value of the imagePositionX property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getImagePositionX() {
        return imagePositionX;
    }

    /**
     * Sets the value of the imagePositionX property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setImagePositionX(REAL value) {
        this.imagePositionX = value;
    }

    /**
     * Gets the value of the imagePositionY property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getImagePositionY() {
        return imagePositionY;
    }

    /**
     * Sets the value of the imagePositionY property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setImagePositionY(REAL value) {
        this.imagePositionY = value;
    }

    /**
     * Gets the value of the imagePositionZ property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getImagePositionZ() {
        return imagePositionZ;
    }

    /**
     * Sets the value of the imagePositionZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setImagePositionZ(REAL value) {
        this.imagePositionZ = value;
    }

}
