//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Image complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Image">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sopClassUid" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="sopInstanceUid" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="imagePlane" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImagePlane" minOccurs="0"/>
 *         &lt;element name="generalImage" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}GeneralImage" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Image", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "sopClassUid",
    "sopInstanceUid",
    "imagePlane",
    "generalImage"
})
public class Image {

    @XmlElement(required = true)
    protected II sopClassUid;
    @XmlElement(required = true)
    protected II sopInstanceUid;
    protected ImagePlane imagePlane;
    protected GeneralImage generalImage;

    /**
     * Gets the value of the sopClassUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getSopClassUid() {
        return sopClassUid;
    }

    /**
     * Sets the value of the sopClassUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setSopClassUid(II value) {
        this.sopClassUid = value;
    }

    /**
     * Gets the value of the sopInstanceUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getSopInstanceUid() {
        return sopInstanceUid;
    }

    /**
     * Sets the value of the sopInstanceUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setSopInstanceUid(II value) {
        this.sopInstanceUid = value;
    }

    /**
     * Gets the value of the imagePlane property.
     * 
     * @return
     *     possible object is
     *     {@link ImagePlane }
     *     
     */
    public ImagePlane getImagePlane() {
        return imagePlane;
    }

    /**
     * Sets the value of the imagePlane property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImagePlane }
     *     
     */
    public void setImagePlane(ImagePlane value) {
        this.imagePlane = value;
    }

    /**
     * Gets the value of the generalImage property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralImage }
     *     
     */
    public GeneralImage getGeneralImage() {
        return generalImage;
    }

    /**
     * Sets the value of the generalImage property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralImage }
     *     
     */
    public void setGeneralImage(GeneralImage value) {
        this.generalImage = value;
    }

}
