//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageAnnotation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageAnnotation">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AnnotationEntity">
 *       &lt;sequence>
 *         &lt;element name="segmentationEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SegmentationEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}SegmentationEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="markupEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="MarkupEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}MarkupEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="imageAnnotationStatementCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImageAnnotationStatement" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AnnotationStatement" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="imageReferenceEntityCollection" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImageReferenceEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImageReferenceEntity" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageAnnotation", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "segmentationEntityCollection",
    "markupEntityCollection",
    "imageAnnotationStatementCollection",
    "imageReferenceEntityCollection"
})
public class ImageAnnotation
    extends AnnotationEntity
{

    protected ImageAnnotation.SegmentationEntityCollection segmentationEntityCollection;
    protected ImageAnnotation.MarkupEntityCollection markupEntityCollection;
    protected ImageAnnotation.ImageAnnotationStatementCollection imageAnnotationStatementCollection;
    protected ImageAnnotation.ImageReferenceEntityCollection imageReferenceEntityCollection;

    /**
     * Gets the value of the segmentationEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ImageAnnotation.SegmentationEntityCollection }
     *     
     */
    public ImageAnnotation.SegmentationEntityCollection getSegmentationEntityCollection() {
        return segmentationEntityCollection;
    }

    /**
     * Sets the value of the segmentationEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageAnnotation.SegmentationEntityCollection }
     *     
     */
    public void setSegmentationEntityCollection(ImageAnnotation.SegmentationEntityCollection value) {
        this.segmentationEntityCollection = value;
    }

    /**
     * Gets the value of the markupEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ImageAnnotation.MarkupEntityCollection }
     *     
     */
    public ImageAnnotation.MarkupEntityCollection getMarkupEntityCollection() {
        return markupEntityCollection;
    }

    /**
     * Sets the value of the markupEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageAnnotation.MarkupEntityCollection }
     *     
     */
    public void setMarkupEntityCollection(ImageAnnotation.MarkupEntityCollection value) {
        this.markupEntityCollection = value;
    }

    /**
     * Gets the value of the imageAnnotationStatementCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ImageAnnotation.ImageAnnotationStatementCollection }
     *     
     */
    public ImageAnnotation.ImageAnnotationStatementCollection getImageAnnotationStatementCollection() {
        return imageAnnotationStatementCollection;
    }

    /**
     * Sets the value of the imageAnnotationStatementCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageAnnotation.ImageAnnotationStatementCollection }
     *     
     */
    public void setImageAnnotationStatementCollection(ImageAnnotation.ImageAnnotationStatementCollection value) {
        this.imageAnnotationStatementCollection = value;
    }

    /**
     * Gets the value of the imageReferenceEntityCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ImageAnnotation.ImageReferenceEntityCollection }
     *     
     */
    public ImageAnnotation.ImageReferenceEntityCollection getImageReferenceEntityCollection() {
        return imageReferenceEntityCollection;
    }

    /**
     * Sets the value of the imageReferenceEntityCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageAnnotation.ImageReferenceEntityCollection }
     *     
     */
    public void setImageReferenceEntityCollection(ImageAnnotation.ImageReferenceEntityCollection value) {
        this.imageReferenceEntityCollection = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImageAnnotationStatement" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AnnotationStatement" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imageAnnotationStatement"
    })
    public static class ImageAnnotationStatementCollection {

        @XmlElement(name = "ImageAnnotationStatement", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<AnnotationStatement> imageAnnotationStatement;

        /**
         * Gets the value of the imageAnnotationStatement property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imageAnnotationStatement property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImageAnnotationStatement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AnnotationStatement }
         * 
         * 
         */
        public List<AnnotationStatement> getImageAnnotationStatement() {
            if (imageAnnotationStatement == null) {
                imageAnnotationStatement = new ArrayList<AnnotationStatement>();
            }
            return this.imageAnnotationStatement;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImageReferenceEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImageReferenceEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imageReferenceEntity"
    })
    public static class ImageReferenceEntityCollection {

        @XmlElement(name = "ImageReferenceEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<ImageReferenceEntity> imageReferenceEntity;

        /**
         * Gets the value of the imageReferenceEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imageReferenceEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImageReferenceEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageReferenceEntity }
         * 
         * 
         */
        public List<ImageReferenceEntity> getImageReferenceEntity() {
            if (imageReferenceEntity == null) {
                imageReferenceEntity = new ArrayList<ImageReferenceEntity>();
            }
            return this.imageReferenceEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="MarkupEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}MarkupEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "markupEntity"
    })
    public static class MarkupEntityCollection {

        @XmlElement(name = "MarkupEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<MarkupEntity> markupEntity;

        /**
         * Gets the value of the markupEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the markupEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMarkupEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link MarkupEntity }
         * 
         * 
         */
        public List<MarkupEntity> getMarkupEntity() {
            if (markupEntity == null) {
                markupEntity = new ArrayList<MarkupEntity>();
            }
            return this.markupEntity;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SegmentationEntity" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}SegmentationEntity" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "segmentationEntity"
    })
    public static class SegmentationEntityCollection {

        @XmlElement(name = "SegmentationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<SegmentationEntity> segmentationEntity;

        /**
         * Gets the value of the segmentationEntity property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the segmentationEntity property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSegmentationEntity().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SegmentationEntity }
         * 
         * 
         */
        public List<SegmentationEntity> getSegmentationEntity() {
            if (segmentationEntity == null) {
                segmentationEntity = new ArrayList<SegmentationEntity>();
            }
            return this.segmentationEntity;
        }

    }

}
