//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ImageAnnotationCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageAnnotationCollection">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}AnnotationCollection">
 *       &lt;sequence>
 *         &lt;element name="person" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}Person" minOccurs="0"/>
 *         &lt;element name="imageAnnotations">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ImageAnnotation" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImageAnnotation" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageAnnotationCollection", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "person",
    "imageAnnotations"
})
public class ImageAnnotationCollection
    extends AnnotationCollection
{

    protected Person person;
    @XmlElement(required = true)
    protected ImageAnnotationCollection.ImageAnnotations imageAnnotations;

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the imageAnnotations property.
     * 
     * @return
     *     possible object is
     *     {@link ImageAnnotationCollection.ImageAnnotations }
     *     
     */
    public ImageAnnotationCollection.ImageAnnotations getImageAnnotations() {
        return imageAnnotations;
    }

    /**
     * Sets the value of the imageAnnotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageAnnotationCollection.ImageAnnotations }
     *     
     */
    public void setImageAnnotations(ImageAnnotationCollection.ImageAnnotations value) {
        this.imageAnnotations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ImageAnnotation" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ImageAnnotation" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "imageAnnotation"
    })
    public static class ImageAnnotations {

        @XmlElement(name = "ImageAnnotation", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<ImageAnnotation> imageAnnotation;

        /**
         * Gets the value of the imageAnnotation property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the imageAnnotation property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getImageAnnotation().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ImageAnnotation }
         * 
         * 
         */
        public List<ImageAnnotation> getImageAnnotation() {
            if (imageAnnotation == null) {
                imageAnnotation = new ArrayList<ImageAnnotation>();
            }
            return this.imageAnnotation;
        }

    }

}
