//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LesionObservationEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LesionObservationEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}Entity">
 *       &lt;sequence>
 *         &lt;element name="lesionUniqueIdentifier" type="{uri:iso.org:21090}II"/>
 *         &lt;element name="isAdditionalObservation" type="{uri:iso.org:21090}BL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LesionObservationEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "lesionUniqueIdentifier",
    "isAdditionalObservation"
})
@XmlSeeAlso({
    GeneralLesionObservationEntity.class,
    TimePointLesionObservationEntity.class
})
public abstract class LesionObservationEntity
    extends Entity
{

    @XmlElement(required = true)
    protected II lesionUniqueIdentifier;
    protected BL isAdditionalObservation;

    /**
     * Gets the value of the lesionUniqueIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getLesionUniqueIdentifier() {
        return lesionUniqueIdentifier;
    }

    /**
     * Sets the value of the lesionUniqueIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setLesionUniqueIdentifier(II value) {
        this.lesionUniqueIdentifier = value;
    }

    /**
     * Gets the value of the isAdditionalObservation property.
     * 
     * @return
     *     possible object is
     *     {@link BL }
     *     
     */
    public BL getIsAdditionalObservation() {
        return isAdditionalObservation;
    }

    /**
     * Sets the value of the isAdditionalObservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BL }
     *     
     */
    public void setIsAdditionalObservation(BL value) {
        this.isAdditionalObservation = value;
    }

}
