//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Quantile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Quantile">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}CharacteristicQuantification">
 *       &lt;sequence>
 *         &lt;element name="bins" type="{uri:iso.org:21090}INT"/>
 *         &lt;element name="selectedBin" type="{uri:iso.org:21090}INT"/>
 *         &lt;element name="minValue" type="{uri:iso.org:21090}REAL"/>
 *         &lt;element name="maxValue" type="{uri:iso.org:21090}REAL"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Quantile", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "bins",
    "selectedBin",
    "minValue",
    "maxValue"
})
public class Quantile
    extends CharacteristicQuantification
{

    @XmlElement(required = true)
    protected INT bins;
    @XmlElement(required = true)
    protected INT selectedBin;
    @XmlElement(required = true)
    protected REAL minValue;
    @XmlElement(required = true)
    protected REAL maxValue;

    /**
     * Gets the value of the bins property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getBins() {
        return bins;
    }

    /**
     * Sets the value of the bins property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setBins(INT value) {
        this.bins = value;
    }

    /**
     * Gets the value of the selectedBin property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getSelectedBin() {
        return selectedBin;
    }

    /**
     * Sets the value of the selectedBin property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setSelectedBin(INT value) {
        this.selectedBin = value;
    }

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setMinValue(REAL value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setMaxValue(REAL value) {
        this.maxValue = value;
    }

}
