//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThreeDimensionGeometricShapeEntity complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThreeDimensionGeometricShapeEntity">
 *   &lt;complexContent>
 *     &lt;extension base="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}GeometricShapeEntity">
 *       &lt;sequence>
 *         &lt;element name="frameOfReferenceUid" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="fiducialUid" type="{uri:iso.org:21090}II" minOccurs="0"/>
 *         &lt;element name="threeDimensionSpatialCoordinateCollection">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ThreeDimensionSpatialCoordinate" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ThreeDimensionSpatialCoordinate" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThreeDimensionGeometricShapeEntity", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "frameOfReferenceUid",
    "fiducialUid",
    "threeDimensionSpatialCoordinateCollection"
})
@XmlSeeAlso({
    ThreeDimensionPoint.class,
    ThreeDimensionPolyline.class,
    ThreeDimensionMultiPoint.class,
    ThreeDimensionEllipsoid.class,
    ThreeDimensionPolygon.class,
    ThreeDimensionEllipse.class
})
public abstract class ThreeDimensionGeometricShapeEntity
    extends GeometricShapeEntity
{

    protected II frameOfReferenceUid;
    protected II fiducialUid;
    @XmlElement(required = true)
    protected ThreeDimensionGeometricShapeEntity.ThreeDimensionSpatialCoordinateCollection threeDimensionSpatialCoordinateCollection;

    /**
     * Gets the value of the frameOfReferenceUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getFrameOfReferenceUid() {
        return frameOfReferenceUid;
    }

    /**
     * Sets the value of the frameOfReferenceUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setFrameOfReferenceUid(II value) {
        this.frameOfReferenceUid = value;
    }

    /**
     * Gets the value of the fiducialUid property.
     * 
     * @return
     *     possible object is
     *     {@link II }
     *     
     */
    public II getFiducialUid() {
        return fiducialUid;
    }

    /**
     * Sets the value of the fiducialUid property.
     * 
     * @param value
     *     allowed object is
     *     {@link II }
     *     
     */
    public void setFiducialUid(II value) {
        this.fiducialUid = value;
    }

    /**
     * Gets the value of the threeDimensionSpatialCoordinateCollection property.
     * 
     * @return
     *     possible object is
     *     {@link ThreeDimensionGeometricShapeEntity.ThreeDimensionSpatialCoordinateCollection }
     *     
     */
    public ThreeDimensionGeometricShapeEntity.ThreeDimensionSpatialCoordinateCollection getThreeDimensionSpatialCoordinateCollection() {
        return threeDimensionSpatialCoordinateCollection;
    }

    /**
     * Sets the value of the threeDimensionSpatialCoordinateCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThreeDimensionGeometricShapeEntity.ThreeDimensionSpatialCoordinateCollection }
     *     
     */
    public void setThreeDimensionSpatialCoordinateCollection(ThreeDimensionGeometricShapeEntity.ThreeDimensionSpatialCoordinateCollection value) {
        this.threeDimensionSpatialCoordinateCollection = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ThreeDimensionSpatialCoordinate" type="{gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM}ThreeDimensionSpatialCoordinate" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "threeDimensionSpatialCoordinate"
    })
    public static class ThreeDimensionSpatialCoordinateCollection {

        @XmlElement(name = "ThreeDimensionSpatialCoordinate", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", required = true)
        protected List<ThreeDimensionSpatialCoordinate> threeDimensionSpatialCoordinate;

        /**
         * Gets the value of the threeDimensionSpatialCoordinate property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the threeDimensionSpatialCoordinate property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getThreeDimensionSpatialCoordinate().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ThreeDimensionSpatialCoordinate }
         * 
         * 
         */
        public List<ThreeDimensionSpatialCoordinate> getThreeDimensionSpatialCoordinate() {
            if (threeDimensionSpatialCoordinate == null) {
                threeDimensionSpatialCoordinate = new ArrayList<ThreeDimensionSpatialCoordinate>();
            }
            return this.threeDimensionSpatialCoordinate;
        }

    }

}
