//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.08 at 12:16:10 PM EDT 
//


package edu.emory.cci.bindaas.datasource.provider.aime4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TwoDimensionSpatialCoordinate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TwoDimensionSpatialCoordinate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="coordinateIndex" type="{uri:iso.org:21090}INT"/>
 *         &lt;element name="x" type="{uri:iso.org:21090}REAL"/>
 *         &lt;element name="y" type="{uri:iso.org:21090}REAL"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TwoDimensionSpatialCoordinate", namespace = "gme://caCORE.caCORE/4.4/edu.northwestern.radiology.AIM", propOrder = {
    "coordinateIndex",
    "x",
    "y"
})
public class TwoDimensionSpatialCoordinate {

    @XmlElement(required = true)
    protected INT coordinateIndex;
    @XmlElement(required = true)
    protected REAL x;
    @XmlElement(required = true)
    protected REAL y;

    /**
     * Gets the value of the coordinateIndex property.
     * 
     * @return
     *     possible object is
     *     {@link INT }
     *     
     */
    public INT getCoordinateIndex() {
        return coordinateIndex;
    }

    /**
     * Sets the value of the coordinateIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link INT }
     *     
     */
    public void setCoordinateIndex(INT value) {
        this.coordinateIndex = value;
    }

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setX(REAL value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link REAL }
     *     
     */
    public REAL getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link REAL }
     *     
     */
    public void setY(REAL value) {
        this.y = value;
    }

}
